"""Initial migration

Revision ID: fa2e4d06ea4a
Revises: 
Create Date: 2025-05-05 11:07:43.387658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2e4d06ea4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom', sa.String(length=120), nullable=True),
    sa.Column('matched_condition', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom_log')
    # ### end Alembic commands ###
